project_id = "default"

[functions.admin-auth]
verify_jwt = false

[functions.admin-config]
verify_jwt = false

[functions.admin-fetch]
verify_jwt = false

[functions.approve-device]
verify_jwt = false

[functions.check-access]
verify_jwt = false

[functions.export-field]
verify_jwt = false

[functions.fetch-config]
verify_jwt = false

[functions.request-access]
verify_jwt = false

[functions.sync-measurements]
verify_jwt = false

[functions.undo-measurement]
verify_jwt = false

